# Generated by Django 6.0.4 on 2026-04-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classperiod',
            options={'ordering': ['start_time']},
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='has_objective',
            new_name='is_objective_applicable',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='has_practical',
            new_name='is_practical_applicable',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='has_written',
            new_name='is_written_applicable',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='objective_max',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='practical_max',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='written_max',
        ),
        migrations.AddField(
            model_name='classperiod',
            name='period_type',
            field=models.CharField(choices=[('CLASS', 'Regular Class'), ('BREAK', 'Lunch/Prayer Break')], default='CLASS', max_length=10),
        ),
        migrations.AddField(
            model_name='subject',
            name='objective_max_marks',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='practical_max_marks',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='written_max_marks',
            field=models.PositiveIntegerField(blank=True, default=100, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='workingday',
            name='day',
            field=models.CharField(choices=[('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], max_length=3, unique=True),
        ),
    ]
