# Generated by Django 6.0.4 on 2026-04-09 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_classperiod_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='My School ERP', max_length=255)),
                ('eiin_number', models.CharField(blank=True, max_length=20, null=True)),
                ('school_start_time', models.TimeField(default='10:00')),
                ('school_end_time', models.TimeField(default='16:00')),
                ('active_academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.academicyear')),
            ],
            options={
                'verbose_name': 'Institution Setting',
                'verbose_name_plural': 'Institution Settings',
            },
        ),
    ]
